server:
  port: 8084

spring.datasource:
  driverClassName: 'org.hibernate.dialect.PostgreSQLDialect'
  url: 'jdbc:postgresql://postgres:5432/postgres'
  username: 'postgres'
  password: 'admin1234'

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

spring.data.redis:
  host: redis
  port: 6379
  database: 0
  timeout: 60000
  password: 