server.port: 8085

api:
  finnhub:
    token: "ck46ck1r01qus81pqgegck46ck1r01qus81pqgf0"
    domain: "finnhub.io"
    base-url: "api/v1"
    endpoints:
      stock:
        profile2: "/stock/profile2"
        quote: "/quote"
        symbol: "/stock/symbol"

redis-key:
  company-profile2: "demo-finnhub:companyprofile2"

spring.datasource:
  driverClassName: 'org.hibernate.dialect.PostgreSQLDialect'
  #driverClassName: 'org.h2.Driver'
  # url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE'
  #url: 'jdbc:h2:mem:testdb'
  #username: 'sa'
  #password:
  url: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'admin1234'
spring:
  h2:
    console:
      enabled: true

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  ## Hibernate Properties
  # properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  # properties.hibernate.dialect: org.h2.Driver
  # Hibernate ddl auto (create, create-drop, validate, update)

spring.data.redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 60000
  password:

spring.sql.init:
  mode: always # always
  platform: h2
  # schema-locations: classpath:ddl/DDL_DROPS.sql, classpath:ddl/DDL_TUSERS.sql, classpath:ddl/DDL_TPOSTS.sql

spring.profiles.active: enableScheduling

#這樣寫的話，原本內建的/actuator/xxx路徑，都會變成/data/xxx，可以用來防止被其他人猜到
management.endpoints.web.base-path: /data

# 可以這樣寫，就會開啟所有endpoints(不包含shutdown)
management.endpoints.web.exposure.include: "*"

# 如果要開啟/actuator/shutdown，要額外再加這一行
management.endpoint.shutdown.enabled: true

# exclude可以用來關閉某些endpoints
# exclude通常會跟include一起用，就是先include了全部，然後再exclude /actuator/beans這個endpoint
# management.endpoints.web.exposure.exclude: beans

# 也可以這樣寫，就只會開啟指定的endpoint，因此此處只會再額外開啟/actuator/beans和/actuator/mappings
# web.exposure.include: beans,mappings

# now we can access more details from endpoint /metrics/health/readiness
management.endpoint.health.group.readiness.show-details: always

management.health.livenessstate.enabled: true
management.health.readinessstate.enabled: true

info.application:
  name: demo-finnhub
  description: A project to handle stock data
  author:
    name: Vincent Lau
    bio: Testing Bio