CREATE TABLE TEACHER (
  id INTEGER NOT NULL,
  name VARCHAR(20) NOT NULL, 
  age NUMERIC(3) NOT NULL, -- NUMERIC(3) means INTEGER
  nationality VARCHAR(2) NOT NULL,
  membership VARCHAR(1) NOT NULL
);