-- 24 Aug
START TRANSACTION;
select * from CUSTOMERS;
INSERT INTO CUSTOMERS VALUES (1, 'XYZ', 'XYZ@GMAIL.COM', 'Y');
rollback;
commit;

-- Primary Key
CREATE TABLE STUDENTS (
	ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(50),
    AGE NUMERIC(3),
    PRIMARY KEY(ID)
);

INSERT INTO STUDENTS (NAME, AGE) VALUES ('JOHN', 23);
INSERT INTO STUDENTS (NAME, AGE) VALUES ('MARY', 18);
SELECT * FROM STUDENTS;

CREATE TABLE SUBJECTS (
	ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(50),
    PRIMARY KEY(ID)
);

INSERT INTO SUBJECTS (NAME) VALUES ('ENGLISH');
INSERT INTO SUBJECTS (NAME) VALUES ('HISTORY');
INSERT INTO SUBJECTS (NAME) VALUES ('MATHS');

-- DDL
CREATE TABLE STUDENT_SUBJECTS (
	ID INTEGER AUTO_INCREMENT,
    STUDENT_ID INTEGER NOT NULL,
    SUBJECT_ID INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(ID),
    FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECTS(ID)
);

-- DML
INSERT INTO STUDENT_SUBJECTS (STUDENT_ID, SUBJECT_ID) VALUES (1, 2);
INSERT INTO STUDENT_SUBJECTS (STUDENT_ID, SUBJECT_ID) VALUES (1, 3);
INSERT INTO STUDENT_SUBJECTS (STUDENT_ID, SUBJECT_ID) VALUES (2, 2);
-- ERROR, FOREIGN KEY CONSTRAINT FAILS
-- INSERT INTO STUDENT_SUBJECTS (STUDENT_ID, SUBJECT_ID) VALUES (2, 4);

-- TRUNCATE (DELETE ALL DATA FROM TABLE)
TRUNCATE TABLE STUDENT_SUBJECTS;
SELECT * FROM STUDENT_SUBJECTS;